Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,54 +1,69 @@
 name: CI/CD for Yii2 App
 
 on:
-  workflow_dispatch:
-  # push:
-  #   branches:
-  #     - main
+  push:
+    branches:
+      - main
 
 jobs:
-  check-ansible:
+  check_Ansible_andrun_playbook:
     runs-on: ubuntu-latest
     steps:
-      - name: Check and install Ansible on EC2
-        uses: appleboy/ssh-action@v1.0.3
-        with:
-          host: ${{ secrets.ANSIBLE_HOST_IP }}
-          username: ${{ secrets.EC2_USER }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          script: |
-            if ! command -v ansible >/dev/null 2>&1; then
-              echo "Ansible not found. Installing..."
-              $ sudo apt update
-              $ sudo apt install software-properties-common
-              $ sudo add-apt-repository --yes --update ppa:ansible/ansible
-              $ sudo apt install ansible
-            else
-              echo "Ansible is already installed."
-            fi
-  setup-ansible-connection-with-target:
-    runs-on: ubuntu-latest
-    needs: check-ansible
-    steps:
-      - name: Connect to EC2 A and run Ansible on EC2 B
-        uses: appleboy/ssh-action@v1.0.3
-        with:
-          host: ${{ secrets.ANSIBLE_HOST_IP }}
-          username: ${{ secrets.EC2_USER }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          script: |
-            # Save TARGET_SSH_KEY into a file
-            echo "${{ secrets.TARGET_SSH_KEY }}" > ~/target_key
-            chmod 600 ~/target_key
+    - name: Checkout code
+      uses: actions/checkout@v4
 
-            # Create a temporary inventory
-            cat > inventory.ini <<EOF
-            [target]
-            ec2-b ansible_host=${{ secrets.DEPLOY_EC_IP }} ansible_user=ubuntu ansible_ssh_private_key_file=~/target_key
-            EOF
+    - name: Setup SSH key
+      run: |
+        mkdir -p ~/.ssh
+        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
+        chmod 600 ~/.ssh/id_rsa
+        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
 
-            # Run Ansible ping test
-            ansible all -i inventory.ini -m ping
+    - name: Run Ansible Playbook
+      run: |
+        ansible-playbook -i "${{ secrets.EC2_HOST }}," ansible/playbook.yml -u ${{ secrets.EC2_USER }} --private-key ~/.ssh/id_rsa
+        # check-ansible:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Check and install Ansible on EC2
+  #       uses: appleboy/ssh-action@v1.0.3
+  #       with:
+  #         host: ${{ secrets.ANSIBLE_HOST_IP }}
+  #         username: ${{ secrets.EC2_USER }}
+  #         key: ${{ secrets.EC2_SSH_KEY }}
+  #         script: |
+  #           if ! command -v ansible >/dev/null 2>&1; then
+  #             echo "Ansible not found. Installing..."
+  #             $ sudo apt update
+  #             $ sudo apt install software-properties-common
+  #             $ sudo add-apt-repository --yes --update ppa:ansible/ansible
+  #             $ sudo apt install ansible
+  #           else
+  #             echo "Ansible is already installed."
+  #           fi
+  # setup-ansible-connection-with-target:
+  #   runs-on: ubuntu-latest
+  #   needs: check-ansible
+  #   steps:
+  #     - name: Connect to EC2 A and run Ansible on EC2 B
+  #       uses: appleboy/ssh-action@v1.0.3
+  #       with:
+  #         host: ${{ secrets.ANSIBLE_HOST_IP }}
+  #         username: ${{ secrets.EC2_USER }}
+  #         key: ${{ secrets.EC2_SSH_KEY }}
+  #         script: |
+  #           # Save TARGET_SSH_KEY into a file
+  #           echo "${{ secrets.TARGET_SSH_KEY }}" > ~/target_key
+  #           chmod 600 ~/target_key
+
+  #           # Create a temporary inventory
+  #           cat > inventory.ini <<EOF
+  #           [target]
+  #           ec2-b ansible_host=${{ secrets.DEPLOY_EC_IP }} ansible_user=ubuntu ansible_ssh_private_key_file=~/target_key
+  #           EOF
+
+  #           # Run Ansible ping test
+  #           ansible all -i inventory.ini -m ping
   # deploy:
   #   runs-on: ubuntu-latest
 
